development: &development
  adapter: mysql
  database: ep_development
  username: root
  password: 
  host: localhost

test:
  <<: *development
  database: ep_test

staging:
  <<: *development
  database: ep_staging

production: 
  <<: *development
  database: ep_production